### ISSUE TITLE
Prometheus configuration in tutorial leads to directory mount error

### ISSUE THREAD

**Issue by BBITWestin** [MicrosoftDocs/mslearn-dotnet-cloudnative#20]
## Issue Description
Following the tutorial instructions for adding Prometheus results in an error where Prometheus attempts to read its configuration file but encounters a directory instead.

## Current Behavior
When following the tutorial steps exactly as written, Prometheus fails to start with the following error:
```bash
level=ERROR source=main.go:593 msg="Error loading config (--config.file=/etc/prometheus/prometheus.yml)" file=/etc/prometheus/prometheus.yml err="read /etc/prometheus/prometheus.yml: is a directory"
```

The error keeps repeating and Prometheus exits with code 2.

## Current Tutorial Configuration
docker-compose.yml section:
```yaml
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
```

## Environment
- Following Microsoft Learn tutorial: https://learn.microsoft.com/en-us/training/modules/implement-observability-cloud-native-app-with-opentelemetry/6-exercise-use-opentelemetry-data-cloud-native-application
